version: '3'

volumes:
  db_data_dev:

networks:
  backend_network_dev:
    driver: bridge
  app_network_dev:
    driver: bridge

services:
  frontend:
    container_name: app_frontend_dev
    image: app_frontend_dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    ports:
      - ${FRONTEND_EXTERNAL_PORT}:${FRONTEND_INTERNAL_PORT}
    environment:
      EXTERNAL_API_URL: ${EXTERNAL_API_URL}
      NEXT_PUBLIC_INTERNAL_API_URL: ${INTERNAL_API_URL}
      NEXT_TELEMETRY_DISABLED: 1
    restart: on-failure
    working_dir: /app-frontend
    command: npm run dev
    volumes:
      - ./frontend/src:/app-frontend/src
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app_network_dev

  backend:
    container_name: app_backend_dev
    image: app_backend_dev
    build:
        context: ./backend
        dockerfile: dev.Dockerfile
    ports:
      - ${BACKEND_EXTERNAL_PORT}:${BACKEND_INTERNAL_PORT}
    environment:
      APP_PORT: ${BACKEND_INTERNAL_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_EXTERNAL_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    restart: on-failure
    working_dir: /app-backend
    command: npm run start:dev
    volumes:
      - ./backend/src:/app-backend/src
      - ./backend/test:/app-backend/test
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:9999" ]
      timeout: 10s
      retries: 5
    networks:
      - backend_network_dev
      - app_network_dev

  db:
    image: postgres:latest
    container_name: app_database_dev
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_INTERNAL_PORT}
    restart: "always"
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      timeout: 10s
      retries: 5
    networks:
      - backend_network_dev